CC = gcc
CFLAGS = -c -g -Wall -m32 -arch i386
LDFLAGS = -m32 -arch i386

decrypt: decrypt_impl.o decrypt.o
	$(CC) $(LDFLAGS) -o decrypt $+

decrypt_test: decrypt_impl.o decrypt_test.o
	$(CC) $(LDFLAGS) -o decrypt_test $+

%.o: %.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	rm -f *.o decrypt_test


